{
    # note: this file is autogenerated by https://github.com/jeff-hykin/rust_flake/publisher/publish.js
    description = "Rust versions setup via fenix";

    inputs = {
        flake-utils.url = "github:numtide/flake-utils";
        nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
        fenix.url = "github:nix-community/fenix";
        fenix.inputs.nixpkgs.follows = "nixpkgs";
        rust-manifest = {
            url = "https://static.rust-lang.org/dist/2024-05-02/channel-rust-1.78.0.toml";
            flake = false;
        };
    };

    outputs = { self, flake-utils, nixpkgs, fenix, rust-manifest, ... }:
        flake-utils.lib.eachSystem (builtins.attrNames fenix.packages) (system:
            let
                pkgs = import nixpkgs { inherit system; };
                localFenix = fenix.packages.${system};
                rustToolchain = (localFenix.fromManifestFile rust-manifest);
                rustPlatform = pkgs.makeRustPlatform {
                    cargo = rustToolchain;
                    rustc = rustToolchain;
                };
            in
                {
                    lib = {
                        rustPlatform = rustPlatform // {
                            info = {
                                version = "1.78.0";
                                channel = "stable";
                                manifestUrl = "https://static.rust-lang.org/dist/2024-05-02/channel-rust-1.78.0.toml";
                                date = "2024-05-02"; 
                            };
                        };
                    };
                    packages = {
                        rust = rustToolchain.rust;
                        default = rustToolchain.rust;
                    };
                }
        )
    ;
}